server:
  port: 9010
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/V1__init_database.sql
    enabled: true
  jpa:
    properties:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        globally_quoted_identifiers: true
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect

spring-doc:
  swagger-ui:
    path: '/swagger-ui.html'
    swagger-ui:
      operationsSorter: method

